version: '3.8'

services:

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3307:3306  # Puerto local 3307 hacia el puerto 3306 en el contenedor
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=bmustdb
      - MYSQL_USER=user123
      - MYSQL_PASSWORD=userpassword
      - TZ=America/Argentina/Mendoza
    networks:
      - express-app

  backend:
    build:
      context: https://github.com/etec-integration-project/etec-pi-2024-backend-Romanchu.git
    container_name: backend
    restart: always
    environment:
      - DATABASE_NAME=bmustdb
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=1234
      - DATABASE_PORT=3306
      - DATABASE_HOST=mysql
    networks:
      - express-app

  frontend:
    build:
      context: https://github.com/etec-integration-project/etec-pi-2024-frontend-Romanchu.git
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    depends_on:
      - backend
    networks:
      - express-app

  nginx:
    build:
      context: https://github.com/etec-integration-project/etec-pi-2024-proxy-Romanchu.git
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "8081:80"  # Exponer puerto 80 de Nginx en el puerto 8081 local
    depends_on:
      - frontend
      - backend
    restart: always
    networks:
      - express-app

networks:
  express-app:
    driver: bridge
